spring:
  application:
    name: yu-ai-code-mother
  profiles:
    active: local
  # mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.100.128:3307/yu_ai_code_mother
    username: root
    password: 123
    hikari:
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      maximum-pool-size: 20
      minimum-idle: 5
  # redis
  data:
    redis:
      host: 192.168.100.128
      port: 6379
      database: 0
      password:
      ttl: 3600 #缓存过期时间 (秒)
server:
  port: 8123
  servlet:
    context-path: /api
# AI
langchain4j:
  open-ai:
    chat-model:
      base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
      api-key: <Your API Key>
      model-name: qwen-plus
      log-requests: true
      log-responses: true
      max-tokens: 8192
    #      max-retries: 3
    #      strict-json-schema: true
    #      response-format: json_object
    streaming-chat-model:
      base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
      api-key: <Your API Key>
      model-name: qwen-plus
      max-tokens: 8192
      log-requests: true
      log-responses: true
    #      max-retries: 1
    reasoning-chat-model:
      base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
      api-key: <Your API Key>
      model-name: qwen-plus
      max-tokens: 32768
      log-requests: true
      log-responses: true
  #      strict-json-schema: true
  #      response-format: json_object
  #      max-retries: 2
  # 智能路由 AI 模型配置
routing-chat-model:
  base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
  api-key: <Your API Key>
  model-name: qwen-plus
  max-tokens: 1000
  log-requests: false
  log-responses: false
# 添加 COS 对象存储配置（需要从腾讯云获取）
cos:
  client:
    host:
    secretId:
    secretKey:
    region:
    bucket:
# Pexels 图片搜索配置
pexels:
  api-key:
# 阿里云 DashScope 配置
dashscope:
  api-key:
  image-model:
# springdoc-openapi
springdoc:
  group-configs:
    - group: 'default'
      packages-to-scan: com.yu.yuaicodemother.controller
# knife4j
knife4j:
  enable: true
  setting:
    language: zh_cn
#监控
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always