spring:
  application:
    name: yu-ai-code-mother
  # mysql
  profiles:
    active: local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yu_ai_code_mother
    username: root
    password: 12
  # redis
  data:
    redis:
      host: localhost
      port: 6379
      password:
      ttl: 3600
  # session 配置
  session:
    store-type: redis
    # session 30 天过期
    timeout: 2592000
server:
  port: 8123
  servlet:
    context-path: /api
    # cookie 30 天过期
    session:
      cookie:
          max-age: 2592000

# 添加 COS 对象存储配置（需要从腾讯云获取）
cos:
  client:
    host: your-custom-domain.com
    secretId: your-secret-id
    secretKey: your-secret-key
    region: ap-shanghai
    bucket: your-bucket-name


# springdoc-openapi
springdoc:
  group-configs:
    - group: 'default'
      packages-to-scan: com.yu.yuaicodemother.controller


# knife4j
knife4j:
  enable: true
  setting:
    language: zh_cn
langchain4j:
  open-ai:
    chat-model:
      base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
      api-key:
      model-name:
      log-requests: true
      log-responses: true
      max-tokens: 32768
      strict-json-schema: true
      response-format: json_object
    streaming-chat-model:
      base-url: https://api.deepseek.com
      api-key: <Your API Key>
      model-name: deepseek-chat
      max-tokens: 8192
      log-requests: true
      log-responses: true
      temperature: 0.7
    reasoning-chat-model:
      base-url: https://api.deepseek.com
      api-key: <Your API Key>
      model-name: deepseek-chat
      max-tokens: 8192
      log-requests: true
      log-responses: true




